#
# Behavior tree nodes for controlling robot hand movement to the left side.
#

MoveToTheSide:
  class_name: fosdem26_autoapms_behavior::VelocityPub
  description: "Condition node that commands the robot hand to move to the left"
  topic: /robot/velocity_cmd
  port_default:
    velocity: -1.0
  hidden_ports:
    - velocity

HandReachedEndPosition:
  class_name: fosdem26_autoapms_behavior::PositionInRange
  description: "Condition node that checks if the robot hand has reached the left end position"
  topic: /robot/position
  port_default:
    low: -1.0
    high: -0.95
  hidden_ports:
    - low
    - high
